version: '3.9'
services:
  pagy:
    build: .
    depends_on: [redis]
    links: [redis]
    ports: [127.0.0.1:1313:1313]
    volumes: [./app:/app]
    image: pagy:latest
    container_name: pagy_app
  base:
    image: redis:alpine
    hostname: redis
    ports: [6379:6379]
    volumes: [./app/data:/data]
    container_name: pagy_base
    command: redis-server --requirepass timestamp
