version: '3.9'
services:
  api:
    build: .
    depends_on: [redis]
    links: [redis]
    ports: [127.0.0.1:1313:1313]
    volumes: [./app:/app]
    image: pagy:latest
    container_name: pagy
  redis:
    image: redis:alpine
    hostname: redis
    ports: [6379:6379]
    volumes: [./app/data:/data]
